apiVersion: v1
kind: Secret
metadata:
  name: health-samurai-secrets
type: Opaque
stringData:
  # Generate a secure random string for this
  # Example: openssl rand -hex 32
  webhook-secret: "REPLACE_WITH_SECURE_SECRET"
