apiVersion: v1
kind: Secret
metadata:
  name: health-samurai-secrets
type: Opaque
stringData:
  # Google OAuth
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  GOOGLE_REDIRECT_URI: ""
  GOOGLE_ALLOWED_DOMAIN: "health-samurai.io"
  # GitHub Webhook
  WEBHOOK_SECRET: ""
  # Zulip Bot
  ZULIP_BOT_EMAIL: ""
  ZULIP_API_KEY: ""
  ZULIP_SERVER: "https://chat.health-samurai.io"
  ZULIP_STREAM: "health-samurai.io"
