apiVersion: v1
kind: ConfigMap
metadata:
  name: health-samurai-config
data:
  GIT_REPO: "https://github.com/HealthSamurai/health-samurai-io-bun.git"
  GIT_BRANCH: "main"
  POLL_INTERVAL: "60"
  PORT: "4444"
