apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: health-samurai-web

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - postgres-secret.yaml
  - app-secrets.yaml

labels:
  - pairs:
      app.kubernetes.io/name: health-samurai-web
      app.kubernetes.io/component: web
    includeSelectors: false
