apiVersion: v1
kind: Service
metadata:
  name: health-samurai-web
  labels:
    app: health-samurai-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4444
      protocol: TCP
      name: http
  selector:
    app: health-samurai-web
