apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-samurai-web
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - site-dev.apki.dev
      secretName: health-samurai-dev-tls
  rules:
    - host: site-dev.apki.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-health-samurai-web
                port:
                  number: 80
